# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: emm-notifications/src/main/proto/emm_pubsub.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "MdmPushNotification" do
    optional :enterprise_id, :string, 1
    optional :event_notification_sent_timestamp_millis, :int64, 2
    repeated :test_push_notification, :message, 3, "TestPushNotification"
    repeated :product_approval_event, :message, 4, "ProductApprovalEvent"
    repeated :install_failure_event, :message, 5, "InstallFailureEvent"
    repeated :app_update_event, :message, 6, "AppUpdateEvent"
    repeated :new_permissions_event, :message, 7, "NewPermissionsEvent"
    repeated :app_restrictions_schema_change_event, :message, 8, "AppRestrictionsSchemaChangeEvent"
  end
  add_message "TestPushNotification" do
  end
  add_message "ProductApprovalEvent" do
    optional :product_id, :string, 1
    optional :approved, :enum, 2, "ProductApprovalEvent.ApprovalStatus"
  end
  add_enum "ProductApprovalEvent.ApprovalStatus" do
    value :UNKNOWN, 0
    value :APPROVED, 1
    value :UNAPPROVED, 2
  end
  add_message "InstallFailureEvent" do
    optional :product_id, :string, 1
    optional :device_id, :string, 2
    optional :user_id, :string, 3
    optional :failure_reason, :enum, 4, "InstallFailureEvent.InstallFailureReason"
    optional :failure_details, :string, 5
  end
  add_enum "InstallFailureEvent.InstallFailureReason" do
    value :UNKNOWN, 0
    value :TIMEOUT, 1
  end
  add_message "AppUpdateEvent" do
    optional :product_id, :string, 1
  end
  add_message "NewPermissionsEvent" do
    optional :product_id, :string, 1
    repeated :requested_permissions, :string, 2
    repeated :approved_permissions, :string, 3
  end
  add_message "AppRestrictionsSchemaChangeEvent" do
    optional :product_id, :string, 1
  end
end

MdmPushNotification = Google::Protobuf::DescriptorPool.generated_pool.lookup("MdmPushNotification").msgclass
TestPushNotification = Google::Protobuf::DescriptorPool.generated_pool.lookup("TestPushNotification").msgclass
ProductApprovalEvent = Google::Protobuf::DescriptorPool.generated_pool.lookup("ProductApprovalEvent").msgclass
ProductApprovalEvent::ApprovalStatus = Google::Protobuf::DescriptorPool.generated_pool.lookup("ProductApprovalEvent.ApprovalStatus").enummodule
InstallFailureEvent = Google::Protobuf::DescriptorPool.generated_pool.lookup("InstallFailureEvent").msgclass
InstallFailureEvent::InstallFailureReason = Google::Protobuf::DescriptorPool.generated_pool.lookup("InstallFailureEvent.InstallFailureReason").enummodule
AppUpdateEvent = Google::Protobuf::DescriptorPool.generated_pool.lookup("AppUpdateEvent").msgclass
NewPermissionsEvent = Google::Protobuf::DescriptorPool.generated_pool.lookup("NewPermissionsEvent").msgclass
AppRestrictionsSchemaChangeEvent = Google::Protobuf::DescriptorPool.generated_pool.lookup("AppRestrictionsSchemaChangeEvent").msgclass
